### ISSUE TITLE
Add Support for hooks

### ISSUE THREAD

**Issue by axos88** [auth0-extensions/auth0-source-control-extension-tools#35]

**Comment by axos88** [comment]
@dirceu @machuga @shawnmclean @jcenturion

**Comment by fyockm** [comment]
@axos88 it's not as simple as adding support for hooks here. we must expose Hooks endpoints via the Auth0 Management. We have this on our roadmap for Q1. Support for Hooks via source control extensions or deploy cli will follow.

**Comment by cb16** [comment]
@fyockm Any news about this issue?

**Comment by shawnmclean** [comment]
Hi, we're currently working on this. We're gathering feedback on hooks and rules and would love some feedback here: https://community.auth0.com/t/tell-auth0-all-your-thoughts-about-rules-hooks/24209/8
