### ISSUE TITLE
Support for having a base directory in the repo?

### ISSUE THREAD

**Issue by lordofthelake** [auth0-extensions/auth0-source-control-extension-tools#39]
For mono-repo scenarios, it would come in handy to be able to group all the Auth0 resources under a base folder, instead of assuming that the directories are always in the root of the repo.

I think this would be a very useful addition, without adding much complexity.

**Comment by stevezau** [comment]
The latest changes to auth0-source-control-extension-tools and the upcoming release to auth0-deploy-cli will support this.

See examples here https://github.com/auth0/auth0-deploy-cli/tree/master/examples

**Comment by fyockm** [comment]
`auth0-deploy-cli@2.0.1` has been released!

**Comment by lordofthelake** [comment]
Is this going to be added to the Auth0 extensions as well?
