### ISSUE TITLE
enabled_clients is ignored in database.json

### ISSUE THREAD

**Issue by zikes** [auth0-extensions/auth0-source-control-extension-tools#58]
I have the following JSON at `/database-connections/PostgreSQL/database.json`, as was generated via `a0deploy export`:

```json
{
  "options": {
    "mfa": {
      "active": true,
      "return_enroll_settings": true
    },
    "passwordPolicy": "good",
    "disable_signup": false,
    "requires_username": false,
    "brute_force_protection": true,
    "strategy_version": 2,
    "enabledDatabaseCustomization": true,
    "customScripts": {
      "get_user": "./get_user.js",
      "login": "./login.js"
    },
    "configuration": {
      "POSTGRESQL_PASSWORD": "..."
    },
    "import_mode": true
  },
  "strategy": "auth0",
  "name": "PostgreSQL",
  "is_domain_connection": false,
  "realms": [
    "PostgreSQL"
  ],
  "enabled_clients": [
    "Client 1",
    "Client 2",
    "..."
  ]
}
```

After each successful deploy of my repository to Auth0, all of the Applications listed under `enabled_clients` will have been disabled and need manually re-enabled. I have tried replacing these client names with their respective IDs, but that has not made a difference.

**Comment by fyockm** [comment]
@zikes this was fixed in latest version. However, I think the JSON name should be settings - `/database-connections/PostgreSQL/settings.json`. Please verify and reopen if necessary.

**Comment by goodspark** [comment]
I'm running into a similar issue. I'm using the Github deploy extension. I've placed a similar `settings.json` file under `database-connections/my-db` and the settings do not update. I also tried `database.json` and no go.

**Comment by zxan1285** [comment]
@goodspark Hi! I've tried to reproduce this issue with Github deploy extension, but it is working just fine for me. Could you please share your `settings.json` content (stripped from any secrets, of course)? Also, could you confirm, that you're using latest (2.6) version of Github extension?

**Comment by goodspark** [comment]
Aha, that must be it! I'm not using 2.6. 2.4. I don't see an option to upgrade but I'm also on a private SaaS setup. I'll see if we can this this upgraded somehow. I assume for a private/hosted setup we have to do this stuff ourselves.
