### ISSUE TITLE
Cannot read property 'getAll' of undefined

### ISSUE THREAD

**Issue by zinosama** [auth0-extensions/auth0-source-control-extension-tools#67]
Version 3.4.0 breaks backup (export) for my private tenant. Problem seems to be coming from `roles`. See error below for details.

```
2019-04-25T01:15:46.683Z - error: Problem running command export during stage load when processing type roles
2019-04-25T01:15:46.683Z - error: Cannot read property 'getAll' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
...
```

**Comment by stevezau** [comment]
Hi @zinosama i just tried and was not able to re-produce the error. Are you using Auth0-deploy-cli ?

What do you mean by private tenant? Are you on the appliance version of auth0?

When you log into your tenant dashboard can you see roles under "Users & Roles"?

The error you are seeing seems to suggest the an incorrect version of node-auth0. It requires the latest version https://github.com/auth0/node-auth0/releases/tag/v2.17.0. How did you upgrade?

**Comment by zinosama** [comment]
Hi @stevezau yes i'm using Auth0-deploy-cli. 

By private tenant, I mean my Auth0 tenant is on appliance hosting. 

When I log into my tenant dashboard, I only see "Users" instead of "Users & Roles".

We are on node auth0: "2.16.0" and  auth0-deploy-cli: "3.1.2". The problem, however, is that the release for v.3.4.0 is a breaking change for our appliance tenant. Since auth0-deploy-cli only has a major-version lock on this library, our services that rely on auth0-deploy-cli failed after fresh deployments.
