### ISSUE TITLE
Temporary rules reordering might conflict with future ruleset

### ISSUE THREAD

**Issue by nicosabena** [auth0-extensions/auth0-source-control-extension-tools#75]
When processing rule changes, the algorithm makes a reorder for conflicting rules (those with the same order number and a different name). 

https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/b2964a698ff26acee4e1d7507c62267648b8ffb3/src/auth0/handlers/rules.js#L90-L102

For the temporary reorder, the max order number from the existing ruleset is used:

https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/b2964a698ff26acee4e1d7507c62267648b8ffb3/src/auth0/handlers/rules.js#L90

The "future" ruleset, however, might have a rule with an order matching any of the temporarily assigned rule order, causing an error. E.g. in the following sequence the order "9" was deemed secure to use as a temporary order number, but a rule with order "9" was present in the set of future rules:

```
2019-10-11T17:37:50.727Z - Temporally re-order Rule {"name":"r1","stage":"login_success","order":9,"id":"rul_aaaaaaaaaa"}
[...]

2019-10-11T17:37:51.426Z - Problem running command import during stage processChanges when processing type rules
2019-10-11T17:37:51.426Z - Problem updating rules {"id":"rul_bbbbbbbbb","name":"r2","enabled":true,"script":"...","order":9,"stage":"login_success"}
APIError: {"statusCode":409,"error":"Conflict","message":"A rule with the same order already exists","errorCode":"rule_conflict"}
error Command failed with exit code 1.
Image file
```

**Comment by nicosabena** [comment]
Yes bot, this is still relevant.

**Comment by mfanto** [comment]
As a workaround for this, you can create empty rules in the tenant dashboard, to force a higher number when reordering. In our case, we had two rules in our tenant, and were deploying two new rules, for a total of four rules. 

To work around, we created two "empty" rules on the tenant dashboard. Then we ran a0deploy. We ended up with the correct four rules on the dashboard.

**Comment by nicosabena** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

Yes, bot, It is relevant. It's an issue to be tracked and eventually be fixed.
